/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;
import model.Header;
import model.HeaderTableModel;
import model.Line;
import model.LineTableModel;
import view.LineTableDialog;

/**
 *
 * @author ahmed
 */
public class invoiceframe extends javax.swing.JFrame {

   


   

   

    /**
     * Creates new form 
     */
    public invoiceframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        headerTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        invcustlbl = new javax.swing.JLabel();
        invnumlbl = new javax.swing.JLabel();
        invdatelbl = new javax.swing.JLabel();
        invtotallbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lineTable = new javax.swing.JTable();
        createinvbtn = new javax.swing.JButton();
        deleteinvbtn = new javax.swing.JButton();
        createitembtn = new javax.swing.JButton();
        deleteitembtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        loadmenuitem = new javax.swing.JMenuItem();
        savemenuitem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "title1", "title2", "title3", "title4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(headerTable);

        jLabel1.setText("invoice num");

        jLabel2.setText("Customer name");

        jLabel3.setText("invoice date");

        jLabel4.setText("invoice total");

        invcustlbl.setText(".");

        invnumlbl.setText(".");

        invdatelbl.setText(".");

        invtotallbl.setText(".");

        lineTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "title1", "title2", "title3", "title4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(lineTable);

        createinvbtn.setText("create new invoice");

        deleteinvbtn.setText("delete invoice");

        createitembtn.setText("create new items");

        deleteitembtn.setText("delete item");

        jMenu1.setText("File");

        loadmenuitem.setText("Load");
        jMenu1.add(loadmenuitem);

        savemenuitem.setText("Save");
        jMenu1.add(savemenuitem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(createinvbtn)
                .addGap(79, 79, 79)
                .addComponent(deleteinvbtn)
                .addGap(125, 125, 125)
                .addComponent(createitembtn)
                .addGap(93, 93, 93)
                .addComponent(deleteitembtn)
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(invtotallbl)
                            .addComponent(invdatelbl)
                            .addComponent(invnumlbl)
                            .addComponent(invcustlbl))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(invnumlbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(invcustlbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(invdatelbl))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(invtotallbl))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createinvbtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deleteinvbtn)
                        .addComponent(deleteitembtn)
                        .addComponent(createitembtn)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(invoiceframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(invoiceframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(invoiceframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(invoiceframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                invoiceframe frame= new invoiceframe();
                frame.setVisible(true);
                 //new HeaderTableDialog().setVisible(true);
               
                frame.controller.LoadFile("header.csv","line.csv");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createinvbtn;
    private javax.swing.JButton createitembtn;
    private javax.swing.JButton deleteinvbtn;
    private javax.swing.JButton deleteitembtn;
    private static javax.swing.JTable headerTable;
    private javax.swing.JLabel invcustlbl;
    private javax.swing.JLabel invdatelbl;
    private javax.swing.JLabel invnumlbl;
    private javax.swing.JLabel invtotallbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable lineTable;
    private javax.swing.JMenuItem loadmenuitem;
    private javax.swing.JMenuItem savemenuitem;
    // End of variables declaration//GEN-END:variables

    private Controller controller=new Controller(this);
    public static SimpleDateFormat Df=new SimpleDateFormat("dd-mm-yyyy") ;
    ArrayList<Header> Header;
    ArrayList <Line> Line;
    HeaderTableModel HeaderTableModel;
    LineTableModel LineTableModel;
    LineTableDialog LineTableDialog;

    public LineTableModel getLineTableModel() {
        return LineTableModel;
    }

    public void setLineTableModel(LineTableModel LineTableModel) {
        this.LineTableModel = LineTableModel;
    }

    public ArrayList<Line> getLine(){
    if(Line==null){
        Line=new ArrayList<>();
    }
    return Line;
    }
    public void setLine(ArrayList<Line> Line){
    
        this.Line=Line;
    }
    
    public ArrayList<Header> getHeader(){
    if(Header==null){
        Header=new ArrayList<>();
    }
    return Header;
    }
    
    public void setHeader(ArrayList<Header> Header){
    
        this.Header=Header;
    }
    
    
    public HeaderTableModel getHeaderTableModel() {
        return HeaderTableModel;
    }

    public void setHeaderTableModel(HeaderTableModel HeaderTableModel) {
        this.HeaderTableModel = HeaderTableModel;
    }

    public JTable getheaderTable(){
    return headerTable;
    }
    

    
    public JTable getLineTable(){
    return lineTable;
    }
    
    public Controller getController(){
    return controller;
    }
    
    public JLabel getInvNumLabel(){
            return invnumlbl;
    }
    public JLabel getInvCustLabel(){
    return invcustlbl;
      }
    
    public JLabel getInvDateLabel(){
    return invdatelbl;
    }
    public JLabel getInvTotalLabel(){
    return invtotallbl;
    }

    public Object getLineTableDialog() {
       return LineTableDialog;
    }

  

    
   

  
   
    
}
